// Generated by React Router

<<<<<<< HEAD
import 'react-router';

declare module 'react-router' {
  type Future = {
    unstable_middleware: false;
  };
}
=======
import "react-router";

declare module "react-router" {
  interface Future {
    unstable_middleware: false
  }
}
>>>>>>> origin/develop
