// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/mainClint": {
    params: {};
  };
  "/signIn": {
    params: {};
  };
  "/signUp": {
    params: {};
  };
  "/auth/clientVariales": {
    params: {};
  };
  "/auth/clientHistory": {
    params: {};
  };
  "/auth/restfull/:method?/:urlB64?/:bodyB64?": {
    params: {
      "method"?: string;
      "urlB64"?: string;
      "bodyB64"?: string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/mainClint" | "/signIn" | "/signUp" | "/auth/clientVariales" | "/auth/clientHistory" | "/auth/restfull/:method?/:urlB64?/:bodyB64?" | "/*";
  };
  "./pages/home.tsx": {
    id: "pages/home";
    page: "/";
  };
  "./layouts/layout.tsx": {
    id: "layouts/layout";
    page: "/mainClint" | "/signIn" | "/signUp" | "/auth/clientVariales" | "/auth/clientHistory" | "/auth/restfull/:method?/:urlB64?/:bodyB64?" | "/*";
  };
  "./pages/authClientPage.tsx": {
    id: "pages/authClientPage";
    page: "/mainClint";
  };
  "./pages/signIn.tsx": {
    id: "pages/signIn";
    page: "/signIn";
  };
  "./pages/signUp.tsx": {
    id: "pages/signUp";
    page: "/signUp";
  };
  "./pages/variables.tsx": {
    id: "pages/variables";
    page: "/auth/clientVariales";
  };
  "./pages/history.server.tsx": {
    id: "pages/history.server";
    page: "/auth/clientHistory";
  };
  "./pages/restfull.tsx": {
    id: "pages/restfull";
    page: "/auth/restfull/:method?/:urlB64?/:bodyB64?";
  };
  "./pages/notFound.tsx": {
    id: "pages/notFound";
    page: "/*";
  };
};