// Generated by React Router

import 'react-router';

declare module 'react-router' {
  type Register = {
    pages: Pages;
    routeFiles: RouteFiles;
  };
}

type Pages = {
  '/': {
    params: {};
  };
  '/mainClint': {
    params: {};
  };
  '/singIn': {
    params: {};
  };
  '/singUp': {
    params: {};
  };
  '/auth/clientVariales': {
    params: {};
  };
  '/auth/clientHistory': {
    params: {};
  };
};

type RouteFiles = {
  'root.tsx': {
    id: 'root';
    page:
      | '/'
      | '/mainClint'
      | '/singIn'
      | '/singUp'
      | '/auth/clientVariales'
      | '/auth/clientHistory';
  };
  './pages/home.tsx': {
    id: 'pages/home';
    page: '/';
  };
  './layouts/layout.tsx': {
    id: 'layouts/layout';
    page:
      | '/mainClint'
      | '/singIn'
      | '/singUp'
      | '/auth/clientVariales'
      | '/auth/clientHistory';
  };
  './pages/authClientPage.tsx': {
    id: 'pages/authClientPage';
    page: '/mainClint';
  };
  './pages/singIn.tsx': {
    id: 'pages/singIn';
    page: '/singIn';
  };
  './pages/singUp.tsx': {
    id: 'pages/singUp';
    page: '/singUp';
  };
  './pages/variables.tsx': {
    id: 'pages/variables';
    page: '/auth/clientVariales';
  };
  './pages/history.tsx': {
    id: 'pages/history';
    page: '/auth/clientHistory';
  };
};
