// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/singIn": {
    params: {};
  };
  "/singUp": {
    params: {};
  };
  "/clientVariales": {
    params: {};
  };
  "/clientHistory": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/singIn" | "/singUp" | "/clientVariales" | "/clientHistory";
  };
  "./app/routes/home.tsx": {
    id: "app/routes/home";
    page: "/";
  };
  "./pages/layout.tsx": {
    id: "pages/layout";
    page: "/singIn" | "/singUp" | "/clientVariales" | "/clientHistory";
  };
  "./pages/singIn.tsx": {
    id: "pages/singIn";
    page: "/singIn";
  };
  "./pages/singUp.tsx": {
    id: "pages/singUp";
    page: "/singUp";
  };
  "./pages/variables.tsx": {
    id: "pages/variables";
    page: "/clientVariales";
  };
  "./pages/history.tsx": {
    id: "pages/history";
    page: "/clientHistory";
  };
};